### PR TITLE
fix: 🐛 gallery img object-fit fill -> cover

### PR DESCRIPTION
**Pull request by zWingz**
修改gallery中图片的`object-fit`属性
从`fill`改成`cover`

### CODE REVIEW

**Comment by Molunerfinn** [comment]
cover有严重的性能问题，为了解决性能问题才从cover换成了fill

**Comment by zWingz** [comment]
https://coderwall.com/p/j5udlw/improve-scroll-performance-of-chrome-when-using-background-size-cover

**Comment by Molunerfinn** [comment]
@zWingz 经测试过了，很吃资源。

**Comment by Molunerfinn** [comment]
相关issue：https://github.com/Molunerfinn/PicGo/issues/175

**Pull request closed without merging**
